# Define how many pages appear per site
paginate = 10

# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "pascallemerrer"
theme = "minimalist"

baseurl = "https://PascalLeMerrer.github.io/blog/public/"
# required for publication on Github
canonifyurls = true

languageCode = "en-us"
title = "Pascal's dev blog"

# Syntax coloring
pygmentsuseclasses = true
PygmentsCodeFences = true


layoutdir = "layouts"
publishdir = "dist"


# Allow tags with spaces and special chars
preserveTaxonomyNames = true

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Params]
    Author = "Pascal Le Merrer"
    site_description = "Pascal's blog about software development."
    location = "Somewhere on Earth"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile-image.jpg"
    header_background = "img/header.jpg"
    header_title = "Pascal's Dev Blog"
    copyright = "Powered by [Hugo](http://gohugo.io). All contents licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "pascallemerrer"
    facebook  = ""
    linkedin  = "pascal-le-merrer-872a478"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "pascallemerrer"
    gplus = ""